# FROM alpine
# CMD ["echo", "Hello from Docker container"]



# FROM ubuntu
# ARG count_img=${count_img:-v1.0.0}
# # ENV count_img=v2.0.0
# RUN echo $count_img
# CMD ["/bin/sh", "-c", "echo $count_img"]


# FROM ubuntu
# ENTRYPOINT ["top","-b"]
# CMD ["-c"]


# FROM alpine
# WORKDIR /app
# COPY file1.txt /data/
# COPY file1.txt /data2
# COPY file1.txt temp/
# COPY folder/ /folderdata/
# # 


# FROM ubuntu AS build1
# WORKDIR /app
# COPY file1.txt /app/
# FROM alpine AS build2
# WORKDIR /app
# COPY --from=build1 /app/file1.txt /app/

